market_id: RETAIL-GAZE-01
section_names:
- left
- middle
- right
cameras:
  CAM-01:
    area_id: A
    reference_width: 640
    reference_height: 480
    shelves:
    - shelf_id: '1'
      rack_id: '1'
      level: 1
      polygon:
      - - 66.0
        - 78.0
      - - 131.0
        - 74.0
      - - 134.0
        - 101.0
      - - 68.0
        - 106.0
    - shelf_id: '2'
      rack_id: '1'
      level: 1
      polygon:
      - - 70.0
        - 107.0
      - - 134.0
        - 101.0
      - - 137.0
        - 127.0
      - - 71.0
        - 131.0
    - shelf_id: '3'
      rack_id: '2'
      level: 1
      polygon:
      - - 224.0
        - 43.0
      - - 339.0
        - 89.0
      - - 334.0
        - 171.0
      - - 224.0
        - 86.0
    - shelf_id: '4'
      rack_id: '2'
      level: 1
      polygon:
      - - 334.0
        - 342.0
      - - 334.0
        - 342.0
      - - 428.0
        - 479.0
      - - 376.0
        - 479.0
    - shelf_id: '5'
      rack_id: '1'
      level: 1
      polygon:
      - - 79.0
        - 155.0
      - - 139.0
        - 151.0
      - - 144.0
        - 184.0
      - - 84.0
        - 192.0
